### ISSUE TITLE
pudl0134 Bibliotheca Cicognara

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#10]

**Comment by kelea99** [comment]
Problem with: https://figgy.princeton.edu/catalog/67a5045a-98d6-4a09-9f8d-cc73fabfd55a

**Comment by cwulfman** [comment]
Should Cicognara really be considered a pudl collection? It's already entirely subsumed by the Cicognara project/resource, isn't it?

**Comment by cwulfman** [comment]
Seems to work now.
