### ISSUE TITLE
pudl0066 Civil War, Society and Political Transition in Guatemala

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#13]

**Comment by cwulfman** [comment]
This project began as METS/MODS, with the items generated by hand from a pre-EAD finding aid to the microfilm.  The METS/MODS, plus a version of pudl0066.ead and a final report (anonymous and undated) can be found in the Subversion repository:http://diglibsvn.princeton.edu/svn/puldi/pudl/branches/development/mdata/pudl0066

**Comment by kelea99** [comment]
@cwulfman was able to get MODs functioning and GNIB is being ingested as ephemera into Figgy. Looking at ingest now. Metadata that is still needed, from what we can see:
1. Barcode:  We will be using Folder Number_Item number (example: BI_0_00009). Unique for each item. *Folder and item numbers in EAD*
2. Folder Number: Folder Number (example: BI_0). Folder numbers not unique for each item
** FYI: Local identifier is the Item number (example: 00009). Local identifier is unique for each item and already in migrated metadata**

3. Subject: Ensure this required field is filled. If not, we need to lift this required field for completion or get stakeholder feedback on what to add. 
4. Language: Language is in the MODS. Needed
5. Collections: Latin American and Iberian Studies Collections

**Comment by cwulfman** [comment]
I've created a larger-scale ticket in Figgy:  https://github.com/pulibrary/figgy/issues/4233

**Comment by kelea99** [comment]
@cwulfman we still need the collection tag "Latin American and Iberian Studies Collections" added to all items, so that they can map to the DPUL site. the GNIB collection is a sub collection of the whole.

**Comment by cwulfman** [comment]
Now in the Latin American and Iberian Studies collection

**Comment by cwulfman** [comment]
Fernando reports many of the items have MODS but no images in Figgy:

>  In the process of browsing the collection in search of images, I found many items that didn’t seem to be loading. Here are the links to some of them:

> https://figgy.princeton.edu/catalog/f2a6fc09-bda2-41ee-9502-4ee24bd5a156

> https://figgy.princeton.edu/catalog/2dce6cea-68ae-488d-9d27-a65e7377ef26

> https://figgy.princeton.edu/catalog/523fb904-3783-4361-941d-6716fb96c24e

> https://figgy.princeton.edu/catalog/b993b8e9-22a4-4b4e-94c4-96861592106d

> https://figgy.princeton.edu/catalog/81500236-6b8c-4eb1-b2a4-4965ba0d732c

> https://figgy.princeton.edu/catalog/ea97116b-96b8-4672-9336-d990eacda9c0

> https://figgy.princeton.edu/catalog/ccb1fb12-5b1c-447a-963b-5067c75d9628

> https://figgy.princeton.edu/catalog/54432d9e-36b3-4017-b9a4-1a684756e02e

> https://figgy.princeton.edu/catalog/be98ff09-5b3d-4ed0-8ca0-510b4d8ad72e

> https://figgy.princeton.edu/catalog/64964df5-5a25-47f3-a60c-39cd4153c102

**Comment by cwulfman** [comment]
See report of problematic items: https://docs.google.com/spreadsheets/d/1vpsLuTlatwU0pTqjxv5OmX4K90v-wrIJ9NfeNAFe75I/edit#gid=521120918

**Comment by cwulfman** [comment]
At least some of the images have been mis-filed (with the previous item, for example).  Cliff will review all the items on the Isilon and move images to the right places; Kim will then update the Figgy objects to match.

**Comment by cwulfman** [comment]
The following subdirectories in diglibdata/pudl/pudl0066/ephemera/PD/PD_7_0_b_3 are empty.  The associated metadata appears, at least in some cases, to duplicate records in the same folder.  These also all have MODS metadata but no corresponding METS.

00370
00372
00373
00375
00376
00379
00382
00383
00384
00385
00387
00391
00397
00398
00400
00402
00403
00408
00411
00449
00452
00456
00458
00464
00467
00469
00476
00477
00478
00479
00480
00481
00483
00484
00485
00486
00489
00490
00491
00493
00494
00495
00496
00497
00498
00500
00503
00504
00505
00506
00507
00508
00509
00511
00512
00513
00514
00517
00518
00519
00520
00521
00522
00523
00524
00525
00526
00527
00528
00529
00530
00531
