### ISSUE TITLE
Create Content for main page of PUDL site 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pudl-migration#2]
New text re: migration and discovery of Digital content for main page to replace "New and Featured Collections" area.

**Comment by kelea99** [comment]
Start of working draft, @cwulfman : https://docs.google.com/document/d/1GqbARqNCSxBRnF7nVnmsmMTi1k9w176z4TfgFD0rmok/edit#

**Comment by cwulfman** [comment]
Incorporated draft language into homepage.html; @kelea99 , you can go ahead and delete the Google Doc draft after reviewing homepage.html.
