### ISSUE TITLE
pudl0044 Fitzgerald Collection

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#20]

**Comment by cwulfman** [comment]
See https://github.com/pulibrary/figgy/issues/1592

Update: the 8 objects in PUDL have already been migrated to Figgy, but the arks need to be updated.  Then we can close this ticket.

**Comment by cwulfman** [comment]
- [x] http://arks.princeton.edu/ark:/88435/9z903115m
- [x] http://arks.princeton.edu/ark:/88435/cc08hg91z (may not have been ingested into Figgy)
- [x] http://arks.princeton.edu/ark:/88435/sf268784s
- [x] http://arks.princeton.edu/ark:/88435/fq977w07f
- [x] http://arks.princeton.edu/ark:/88435/bc386k51p
- [x] http://arks.princeton.edu/ark:/88435/jw827c96v
- [x] http://arks.princeton.edu/ark:/88435/kh04dq988
- [x] http://arks.princeton.edu/ark:/88435/x346d693p

**Comment by cwulfman** [comment]
Kim, would you please ask the curators to provide links to the proper finding-aid components for the following two items:


 http://arks.princeton.edu/ark:/88435/cc08hg91z  -->supplied by Chloe Pfendler: http://pudl.princeton.edu/objects/cc08hg91z = C0101_c000668
 http://arks.princeton.edu/ark:/88435/kh04dq988 --> supplied by Chloe Pfendler: http://arks.princeton.edu/ark:/88435/kh04dq988 = C0188_c00003

If possible, it would also be useful for them to verify that they have been properly ingested into Figgy.

**Comment by kelea99** [comment]
@cwulfman : contacted Chloe Pfendler from SC, who has worked/is working on Fitzgerald as a good place to start.

**Comment by cwulfman** [comment]
pudl0044/823463 is http://pudl.princeton.edu/objects/cc08hg91z and it is C0101/c000668

**Comment by kelea99** [comment]
Looking at this one. what more has to be done?

**Comment by kelea99** [comment]
Ok. the missing item is part of C0101 as the information from chloe says above (I got it from the PUDL information).  It has a Figgy collection already: https://figgy.princeton.edu/catalog/b35decb8-345b-4184-9dbc-182e49d1863f. we can add it to that collection.

**Comment by cwulfman** [comment]
Ingested from Isilon and linked to https://findingaids.princeton.edu/catalog/C0101_c000668

https://figgy.princeton.edu/catalog/f55cf1ad-a602-4617-92ee-3208ec63700d
