### ISSUE TITLE
pudl0025 Latin American Posters Collection

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#32]

**Comment by cwulfman** [comment]
migrated; waiting on QA

**Comment by kelea99** [comment]
PUDL0025 needs collection tag: Latin American and Iberian Studies Collections added to all items so that it maps to DPUL exhibit.

**Comment by kelea99** [comment]
I can do this one. Nope. correction. I cannot. Part of an ephemera collection. I am going to forward this to. Gabrielle and Fernando for QA

**Comment by kelea99** [comment]
Heard from Gabrielle. The posters have  been in the "Needs QA" state for three years now, because they would like to have to take another look at the originals. But once they are ready to go public, She will the "All in Production" button. Closing ticket.
