### ISSUE TITLE
pudl0020 Nineteenth-century sheet music collection

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#39]

**Comment by cwulfman** [comment]
These are in Figgy, marked as pending; the arks haven't been changed

**Comment by kelea99** [comment]
@cwulfman these are being done by Brittany in Mendel and her staff.

**Comment by kelea99** [comment]
@escowles should we change the arks on these?

**Comment by escowles** [comment]
If the existing ARKs are in the MARC records, they should get updated automatically when the items are completed.

Or are there other existing ARKs that need to be added?

**Comment by kelea99** [comment]
I would assume cliff means there are existing arks.   if so, Kate has this ark thing down beautifully now and we can use her task?

**Comment by kelea99** [comment]
Check on arks before closing

**Comment by kelea99** [comment]
Items being reviewed by Brittany.

**Comment by kelea99** [comment]
met with Brittany.All MODS are in hand with Brittany on a server. All images have been migrated into figgy, approved by Brittany. CLosing ticket. all done on the PUDL sunsetting end.
