### ISSUE TITLE
pudl0009 Princeton University Historical Postcard Collection

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#43]
See pulibrary/figgy#1580

**Comment by cwulfman** [comment]
This collection is similar to Grounds and Buildings, in that there is detailed item-level metadata in the METS/MODS from the PUDL that doesn't match the descriptive granularity of the EAD.  One solution would be to make a multivolume work for each component in the EAD and ingest each METS/MODS object as a volume of one of those multivolume works.  A considerable amount of metadata (publishers, multiple subject headings) would be lost this way.

**Comment by kelea99** [comment]
From Alexis:

Christa has finished associating finding aid components on the [spreadsheet](https://docs.google.com/spreadsheets/d/1tS6Og1YMQsPcYYJK5gsrrEO1Dlo9zgkIGStURe4LKi8/edit#gid=1650573101) (https://docs.google.com/spreadsheets/d/1tS6Og1YMQsPcYYJK5gsrrEO1Dlo9zgkIGStURe4LKi8/edit#gid=1650573101)

There are a small number of fixes to make in the item-level metadata—there are few enough that we could potentially do these by hand in Figgy, but if it is best to make the changes in the spreadsheet, please let us know.

 Regarding the DPUL exhibition, we would like to get some input from Public Services and then perhaps have a meeting with you to discuss.

**Comment by kelea99** [comment]
i completed all of these. waiting for stakeholders to say we are done

**Comment by cwulfman** [comment]
May I mark this task as complete, @kelea99 ?

**Comment by kelea99** [comment]
Closing.
