### ISSUE TITLE
pudl 0125 Print Ephemera from the 2013 Moscow Mayoral Election

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#44]

**Comment by kelea99** [comment]
@kelea99  will contact Thomas and Anna to ask them about the status of this collection.

**Comment by kelea99** [comment]
This will be its own ephemera project and the title will be: "Print Ephemera from the 2013 Moscow Mayoral Election"

The ephemera project should also be tagged tagged w/ Princeton Slavic Collections.

Confirmed by Thomas Keenan

**Comment by cwulfman** [comment]
So I will ingest this as I did GNIB -- a clone of the Ukraine Ephemera process.

**Comment by kelea99** [comment]
yup. that is how i understand it.

**Comment by kelea99** [comment]
@cwulfman was this ingested as an ephemera project like discussed above?

**Comment by kelea99** [comment]
Ah, i see the problem. it was ingested as "Princeton Slavic Collections" Project. It needs to be  titled: Print Ephemera from the 2013 Moscow Mayoral Election

The secondary collection tag (Princeton Slavic Collections) needs to be added at the item level, in the collections pulldown menu.
