### ISSUE TITLE
pudl0001 Scheide Library: Fifteenth-Century Printing

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#47]

**Comment by kelea99** [comment]
All have been ingested in figgy and all but 1 complete.  Why was this one flagged?? @escowles @roelmoon, ideas? https://figgy.princeton.edu/catalog/923bb0d8-7e1b-4dfa-b66e-ce75770aeebe

I am closing the ticket, regardless,  as all items have MARC records with bib ids noted in PUDL and have been ingested into figgy.

**Comment by escowles** [comment]
Unfortunately, I don't know why this item was flagged — but it is public and showing up in OL, so I think it's fine.

**Comment by kelea99** [comment]
Ok. ill keep the issue closed, then. Thank you!
