### ISSUE TITLE
pudl0083 La grotte de Versailles

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#55]

**Comment by cwulfman** [comment]
Already migrated; see pulibrary/figgy#3962.

Now we need to 

- update the PUDL page
- create DPUL exhibit?

**Comment by cwulfman** [comment]
pudl0083/2012 has not been migrated.

**Comment by kelea99** [comment]
PUDL0083/2012 and PUDL0083/2013 subdirectories contain selections from both versailles plate collections. although this should not be the norm, we should ensure the numbers for each collection match up in figgy and PUDL before closing tickets. thoughts, @cwulfman ?

**Comment by cwulfman** [comment]
I think that, in cases like this, we should specify those sub-directories/subcollections in the ticket, either as checkable boxes or as subtasks.

**Comment by kelea99** [comment]
I did, in the ticket for the versailles collection I was working on? see [ticket](https://app.zenhub.com/workspaces/pudl-migration-5eb16df8c43e55b9970b335f/issues/pulibrary/pudl-migration/54)

**Comment by cwulfman** [comment]
Discussed and resolved in #54
