### ISSUE TITLE
Why is [Engelmann Archive of Proofs and Samples] not migrated from PUDL to figgy?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pudl-migration#6]
@cwulfman I can find [this](http://pudl.princeton.edu/objects/3484zk471) nowhere in the documentation from PUDL sundowning items. Its not in figgy under this title, the bib id, or the catalog title (https://catalog.princeton.edu/catalog/8555444). No GitHub tickets for it that I can find. Went through what I could find for PUDL [migration fails/successes](https://github.com/pulibrary/pudl_mets_compiler/blob/plum_migration/ga_migration_progress.md#fail) with GA as well. Zip. Any memories of this one?

**Comment by kelea99** [comment]
@escowles  do you have any memory as to why this was not migrated? if there is no reason, may we?

**Comment by escowles** [comment]
I can't find any mention of it in my spreadsheets, in Figgy, the compiled METS files from PUDL, or anywhere. Looks like a very straightforward MVW, so I think we should just ingest it.

**Comment by kelea99** [comment]
Ok. Making ticket for it in figgy now.

**Comment by cwulfman** [comment]
This is in pudl0130:
```sh
deploy@lib-proc6:/mnt/diglibdata/pudl/pudl0130$ ls -l
total 0
drwxr-xr-x 2 deploy www-data 0 Mar 27  2017 10149154
drwxr-xr-x 2 deploy www-data 0 Sep  8  2015 3051613
drwxr-xr-x 2 deploy www-data 0 Jan 18  2017 5240761
drwxr-xr-x 2 deploy www-data 0 Mar 25  2016 6109684
drwxr-xr-x 2 deploy www-data 0 Oct 23  2014 8555444
drwxr-xr-x 2 deploy www-data 0 Dec  1  2014 gc060
```

NB 8555444 doesn't appear to be a bibid (it doesn't appear in the catalog).  These seem to be Graphic Arts materials.

**Comment by kelea99** [comment]
Closing this ticket. #3932 is the ingest request for this item.
