### ISSUE TITLE
 8555444:Engleman (#3932)

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#63]
ingest as MVW + Link to MARC record KEL will do

**Comment by kelea99** [comment]
ingest issues. @hackmastera helping with this one. Ticket opened:  https://github.com/pulibrary/figgy/issues/4004

**Comment by kelea99** [comment]
ingested and complete. https://figgy.princeton.edu/catalog/49add4a8-e4fc-4ddf-a533-b335f9b21b18
