### ISSUE TITLE
ingest GC060

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#65]
- GC060: 2 oversized scrapbooks (2 volumes)  prepared by Elmer Adler prepared by GA. Not cataloged at the time. Title: "Princeton print club, 1941-1945". Just tiffs. once cataloged with a bib record, we can ingest this as is. KEL can do. Contact Jennifer Baxmeyer

**Comment by cwulfman** [comment]
This item has been cataloged now.  There are three bib records for [The] Princeton Print Club 1941-1945:

item | bibid | call no
-----|------|--------
volume 1 | 10645371     | E Row 1/GC060/Oversize/Princeton Print Club/Scrapbook 1 GA 2014.01072
volume 2 | 10665094    | E Row 1/GC060/Oversize/Princeton Print Club/Scrapbook 2 GA 2014.01073
single item | 10640579 | D Alcove/GC060/Tall Carton/Princeton Print Club/Ephemera

@kelea99 Are these all the same thing?

**Comment by kelea99** [comment]
after conversation with @cwulfman :
We will be linking each volume to its own Marc record at ingest (Volume 1: 10645371 ; Volume 2: 10665094). @kelea99 will be contacting Jennifer B. alerting her to this. If she feels 10640579 should be noted somewhere in both records, she may do so.  

update: Jennifer B. contacted via slack. information sent.

**Comment by ghost** [comment]
Are there two copies? Why are there 3 MARC records? If this a two-volume resource, the two individual bibs should be sufficient. The third bib seems redundant.

**Comment by kelea99** [comment]
@jbaxmeyer, I will write to Julie M. to ask if there is a second copy or separate collection the 3rd Marc record relates to. If not, I say we nix the third bib. writing to her now.

**Comment by cwulfman** [comment]
volumes 1 & 2 have been ingested:

- https://figgy.princeton.edu/catalog/ac14913e-7482-4dc6-b2a1-fe0976943bc4
- https://figgy.princeton.edu/catalog/15421c99-6bc7-45a1-9c9c-26308d1c80b0

**Comment by kelea99** [comment]
Update from Julie Melby. We will keep that third MARC record. it is for a separate item, @cwulfman .  So this ticket is complete! Closing. Information from Julie regarding the third Marc: 
Hi Kim, thanks so much. There is a 3rd box so yes, there should be 3 records. The ephemera collection was never completely catalogued but very important so we can find this one single box. When I can, I'll pull it and see if it can't be better described. Julie (edited)
