### ISSUE TITLE
ingest 3051613

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#66]
3051613: each one has its own separate VRA record. 

@escowles there are separate Marc records for each plate (presumably) but slightly richer VRA metadata in the PUDL. 

@kelea99 can do a representative sample of what exactly is missing in the Marc. but what is the preferred way forward?

**Comment by kelea99** [comment]
@cwulfman I spoke with @escowles yesterday about this. We should proceed with attaching all plates to the corresponding Marc records and download/preserve the VRA metadata. The MARC records may be enhanced by metadata specialists with the VRA data at a later date.

**Comment by cwulfman** [comment]
Is there some mapping between the sub-folder names and those MARC records?  E.g., how does one map `pudl0130/3051613/ga_2014_00378` to a BIBID?

**Comment by kelea99** [comment]
Good question. Let me have a look, @cwulfman

**Comment by kelea99** [comment]
ok, @cwulfman . mapping finds (PUDL item example being used: http://pudl.princeton.edu/objects/z603r099p) --see location info: GA 2014.00067

seems we can use the following as the unique identifier:

1. the subdirectory for each image from the pudl share on the isilon for the collection (ga_2014_00067) mapped to...
2. the 852 field of the MARC: GA 2014.00067 (cat record link: https://catalog.princeton.edu/catalog/10642869/staff_view)

Sound good? can you magic that on your end? I can only link items via bib ids/component ids with my skillz.

**Comment by cwulfman** [comment]
@kelea99 what is the relationship, if any, between pudl0130/3051613 and https://findingaids.princeton.edu/collections/RTC01/c308?

**Comment by cwulfman** [comment]
For Mark Z, create a spreadsheet w/info from the VRA/METS, so he can generate a Voyager report that links the GA ids with BibIDs, so we can ingest each plate into Figgy by its BibID

**Comment by cwulfman** [comment]
https://docs.google.com/spreadsheets/d/1sazjB0Hm7ERtRoWUzWvMZLMPe5MGg0Jve6X8plLz9pc/edit#gid=1019581632

Waiting for Mark Z to approve

**Comment by cwulfman** [comment]
Ingested as collection pudl0130 https://figgy.princeton.edu/catalog?utf8=✓&q=pudl0130
