### ISSUE TITLE
missing image in pudl0130/3051613 (Rowlandson)

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#68]
E, [2020-07-01T23:45:02.520311 #2841] ERROR -- : Error: BulkIngestService: Directory is empty: /mnt/diglibdata/pudl/pudl0130/3051613/ga_2014_00803

It is in the catalog: https://catalog.princeton.edu/catalog/10660281

**Comment by kelea99** [comment]
Kim  will write to  Julie Mellby about this

**Comment by kelea99** [comment]
Contacted Julie M.  about this.

**Comment by kelea99** [comment]
Julie has paged the missing plate and will be ready whenever it can be added to the studio pipeline. Contacted @roelmoon.

**Comment by kelea99** [comment]
Done
