### ISSUE TITLE
Make static page for "Collections" in PUDL site and change title to "Collections on the Move"

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pudl-migration#7]
Static page with the expectation of adding icon/info for collections that have been migrated to figgy. Redirects needed for collection URLs and all arks.

**Comment by cwulfman** [comment]
Is this ticket still valid?  We've incorporated all the collections into the new static home page.  We just need to make sure the collections/ route points to the static homepage.

**Comment by cwulfman** [comment]
home page (index.html) has been made static, so accomplishes the same thing.
