### ISSUE TITLE
Board of Trustees Minutes. Volumes I-XII (pudl0004)

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#71]
http://arks.princeton.edu/ark:/88435/7w62f826z. points to http://pudl.princeton.edu/objects/7w62f826z

pudl0004 does not appear to have been migrated to Figgy.

[https://app.zenhub.com/files/261482679/e8499838-f751-42ef-95b1-5aa90c1a43b3/download](https://app.zenhub.com/files/261482679/e8499838-f751-42ef-95b1-5aa90c1a43b3/download)

https://findingaids.princeton.edu/catalog/AC120 points back to the PUDL in some cases, and in others (e.g., https://findingaids.princeton.edu/catalog/AC120_c0003)  to an old typed transcription.

AC120 also contains numerous bad headings (e.g. _1824 April 13-1850 June 26, 1824 April 13-1850 June 26_)

Proposed actions:

Ingest pudl0004 into Figgy in a Figgy collection (pudl0004) and publish in DPUL.  Redirect ark to DPUL collection.

**Comment by escowles** [comment]
👍🏻 Ingesting into Figgy and pointing the ARK to DPUL sounds good to me.

**Comment by ccleeton** [comment]
I have had a brief discussion with our Mudd Digital curation team about this collection. We are fine with just getting these into figgy. I am going to check with the rest of our Mudd staff to see if we need to have them in DPUL or not.

**Comment by cwulfman** [comment]
Just get the rest of the images into Figgy and linked to FA or cat records.

**Comment by kelea99** [comment]
heard from roel that folks couldnt get to the items in PUDL, but things are back up and running now.

**Comment by cwulfman** [comment]
@kelea99 can we close this issue now?

**Comment by cwulfman** [comment]
https://figgy.princeton.edu/catalog/474c056f-24fe-4f60-a30c-019268447a64
