### ISSUE TITLE
Ivan Susanin (UPenn item) not migrated to Figgy from PUDL. More information needed

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pudl-migration#80]
This item was part of the DIgital Library Bookshelf in PUDL.  The location is noted as being "Van Pelt Library, University of Pennsylvania Library".  @kelea99 will contact SC/Mendel to determine how to proceed. 

Item is on the Isilon (PUDL0018). T.12a, T.12b, T12 Supplement. We would lose the structure from PUDL, though. 

PUDL link: pudl.princeton.edu/objects/w9505053d

**Comment by kelea99** [comment]
From @jpstroop : The long and short of it is that the collected critical/urtext/etc. works of Russian composers are hard to get...In 2006 a musicology grad student needed this and we did not have a copy, nor could we get one loaned to us long-term, and it was needed for his dissertation. It was decided to do high-res scan while we had it.  The music librarian at Penn, Dick Griscom, who just retired last year, gave us a verbal OK to put it up on our site.

Way forward: in order to migrate the structural metadata, we need a MARC record to ingest to in figgy.  @kelea99 sent request to cataloging issues with links to the PUDL item, the record at UPenn for the complete work, and search results for records describing the items we digitized here at PUL (T.12 a, b, suppl)*.  one record is available @cwulfman will migrate item/structure to figgy and it will be made available via the online catalog.

*Brittany from Mendel is being kept in the loop and will also look for record examples that might help cataloging. 


PUDL: http://pudl.princeton.edu/objects/w9505053d

UPenn complete work: https://franklin.library.upenn.edu/catalog/FRANKLIN_991827123503681

Bit that we have (examples from WorldCat): https://www.worldcat.org/title/ivan-susanin/oclc/474858008&referer=brief_results

**Comment by kelea99** [comment]
just confirmed: Brittany agrees. She would use the example from world cat above for the bit we have here.

**Comment by kelea99** [comment]
Just in case, Ill add the MMSID: 99125378828406421

**Comment by cwulfman** [comment]
Ingested: https://figgy.princeton.edu/catalog/f69c6105-d2f3-41f2-b841-8b1e3ea13ea3

**Comment by kelea99** [comment]
Reopening. the structural metadata was not migrated. @cwulfman can you have a look ?

**Comment by cwulfman** [comment]
I did not try to migrate the structural metadata.  I thought we agreed to ignore it (unless Marvin Bielawski wants to do it again)

**Comment by kelea99** [comment]
Hi! No. the only reason why you were assigned to do it versus me was because of the structural metadata needing to be migrated

**Comment by kelea99** [comment]
@escowles @tpendragon , can you help with this? thanks!

**Comment by escowles** [comment]
I think we can ingest this with the `import:mets` rake task, which will migrate the structure from the METS structmap — here's the code that parses the bib id from the METS: https://github.com/pulibrary/figgy/blob/main/app/models/mets_document.rb#L28 — putting the bibid in the mets file should make it just work with the existing rake task.

**Comment by tpendragon** [comment]
We used to migrate these via a METS file @jpstroop would provide. I'm not really sure how to get that out of the PUDL. Is this happening a lot or should we just manually migrate that structure for this item?

**Comment by kelea99** [comment]
Ill just do it manually. standby.

**Comment by kelea99** [comment]
Finished the first volume.  I think its good enough. Ill finish the other two tomorrow: https://figgy.princeton.edu/catalog/871cd10d-9cfa-493a-828a-b69243153330

**Comment by kelea99** [comment]
structural metadata copied over to figgy and complete (order and structure manager). marked private. completed in figgy. closing ticket
https://figgy.princeton.edu/catalog/f69c6105-d2f3-41f2-b841-8b1e3ea13ea3

**Comment by kelea99** [comment]
changed to open. restricted downloads. send figgy url and ark to Kevin Connell to add to the alma record.
